// Code generated by goctl. DO NOT EDIT.
package types

type OrderReq struct {
	Id string `path:"id"`
}

type OrderReply struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Gender       string `json:"gender"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
